import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

// Parse JSON request bodies
app.use(express.json({ limit: '10mb' }));

// Shared Gemini SDK client
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

// Endpoint to analyze logs, df outputs, and provide clean-up tips
app.post("/api/gemini/analyze", async (req, res) => {
  const { sysInfo, pastedContent } = req.body;

  if (!pastedContent || pastedContent.trim() === '') {
    return res.status(400).json({ error: "Pasted terminal outputs or logs must not be empty." });
  }

  const systemInstruction = `You are an expert system administrator specializing in ChromeOS, Crostini Linux container (Debian), and Android runtime environment (ARC++). 
Analyze the pasted text containing system logs, file disk space reports (like 'df -h' or 'du -h'), or terminal directory contents.
Provide an assessment of storage hogs, identify if specific folders/files are safe to delete, and write exact, extremely safe commands to clean them up.
Device Context: Chromebook Model: HP Chromebook 14 G7, OS Version: ${sysInfo?.chromeOsVersion || 'ChromeOS'}, Linus Subsystem: ${sysInfo?.hasLinux ? 'Active' : 'Muted'}, Android subsystem: ${sysInfo?.hasAndroid ? 'Active' : 'Muted'}.

Your output MUST be a valid JSON object matching this schema exactly:
{
  "overview": "Clear summary of space hogs, overall disc status, and assessment.",
  "itemsDetected": [
    {
      "name": "Name of the storage hog / directory / log file",
      "path": "/path/to/directory or file (if applicable)",
      "size": "Estimated size (e.g. '1.2 GB' or 'unknown')",
      "isSafeToDelete": true/false indicator,
      "explanation": "Human-friendly explanation about what this file/folder is, why it was created, and consequence of deletion.",
      "cleanupCommand": "Safe terminal command to safely wipe / empty / prune this item (e.g., 'rm' for files, 'truncate' for active logs, or apt-get clean/docker prune)"
    }
  ],
  "preventativeMeasures": "Actionable, Chromebook-specific guidelines or tips to prevent this space from building up again."
}

Do not run harmful or destructive commands. Be exceptionally precise with file paths and safe command choice (e.g. suggest 'truncate -s 0 ...' for active log files instead of 'rm' which might break running service handles).`;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: `Pasted log or terminal disk output:
\`\`\`
${pastedContent}
\`\`\``,
      config: {
        systemInstruction: systemInstruction,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          required: ["overview", "itemsDetected", "preventativeMeasures"],
          properties: {
            overview: { type: Type.STRING },
            itemsDetected: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                required: ["name", "isSafeToDelete", "explanation"],
                properties: {
                  name: { type: Type.STRING },
                  path: { type: Type.STRING },
                  size: { type: Type.STRING },
                  isSafeToDelete: { type: Type.BOOLEAN },
                  explanation: { type: Type.STRING },
                  cleanupCommand: { type: Type.STRING }
                }
              }
            },
            preventativeMeasures: { type: Type.STRING }
          }
        },
        temperature: 0.2
      }
    });

    const textOutput = response.text;
    if (!textOutput) {
      throw new Error("No response generated by Gemini API.");
    }

    try {
      const parsed = JSON.parse(textOutput);
      return res.json(parsed);
    } catch (parseErr) {
      console.error("Failed to parse Gemini output as JSON. Output was:", textOutput);
      return res.status(500).json({
        error: "Failed to parse analysis results from AI provider.",
        rawText: textOutput
      });
    }

  } catch (error: any) {
    console.error("Gemini analysis error:", error);
    return res.status(500).json({ error: error.message || "An error occurred during log analysis." });
  }
});

// Serve static assets or mount Vite dev middleware
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    console.log("Starting server in development mode with active Vite routing...");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    console.log("Starting server in production mode...");
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*all', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer().catch((err) => {
  console.error("Failed to start server:", err);
});
